# .github/workflows/llm-security.yml
name: LLM Security Check
on: [push, pull_request]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Ballesty-Liam/llm-security-action@v1